-- Migration 108: Adiciona colunas executor faltantes em produção
-- Usa ADD COLUMN IF NOT EXISTS — seguro mesmo se já existirem

-- procedimentos_coroa_implante
ALTER TABLE procedimentos_coroa_implante
  ADD COLUMN IF NOT EXISTS escaner_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS escaner_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS escaner_executado_por varchar,
  ADD COLUMN IF NOT EXISTS escaner_data date,
  ADD COLUMN IF NOT EXISTS envio_arquivo_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS envio_arquivo_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS envio_arquivo_executado_por varchar,
  ADD COLUMN IF NOT EXISTS envio_arquivo_data date,
  ADD COLUMN IF NOT EXISTS moldagem_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS moldagem_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS moldagem_executado_por varchar,
  ADD COLUMN IF NOT EXISTS moldagem_data date,
  ADD COLUMN IF NOT EXISTS vg_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS vg_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS vg_executado_por varchar,
  ADD COLUMN IF NOT EXISTS vg_data date,
  ADD COLUMN IF NOT EXISTS env_lab_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS env_lab_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS env_lab_executado_por varchar,
  ADD COLUMN IF NOT EXISTS env_lab_data date,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executado_por varchar,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_data date,
  ADD COLUMN IF NOT EXISTS prova_coping_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS prova_coping_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS prova_coping_executado_por varchar,
  ADD COLUMN IF NOT EXISTS prova_coping_data date,
  ADD COLUMN IF NOT EXISTS envio_lb_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS envio_lb_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS envio_lb_executado_por varchar,
  ADD COLUMN IF NOT EXISTS envio_lb_data date,
  ADD COLUMN IF NOT EXISTS recebimento_lab_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS recebimento_lab_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS recebimento_lab_executado_por varchar,
  ADD COLUMN IF NOT EXISTS recebimento_lab_data date,
  ADD COLUMN IF NOT EXISTS paciente3_executor_id uuid REFERENCES dentistas(id),
  ADD COLUMN IF NOT EXISTS paciente3_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS paciente3_executado_por varchar,
  ADD COLUMN IF NOT EXISTS paciente3_data date;

-- procedimentos_fixa_zirconia (mesmas etapas que coroa_implante)
ALTER TABLE procedimentos_fixa_zirconia
  ADD COLUMN IF NOT EXISTS escaner_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS escaner_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS escaner_executado_por varchar,
  ADD COLUMN IF NOT EXISTS escaner_data date,
  ADD COLUMN IF NOT EXISTS envio_arquivo_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS envio_arquivo_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS envio_arquivo_executado_por varchar,
  ADD COLUMN IF NOT EXISTS envio_arquivo_data date,
  ADD COLUMN IF NOT EXISTS moldagem_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS moldagem_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS moldagem_executado_por varchar,
  ADD COLUMN IF NOT EXISTS moldagem_data date,
  ADD COLUMN IF NOT EXISTS vg_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS vg_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS vg_executado_por varchar,
  ADD COLUMN IF NOT EXISTS vg_data date,
  ADD COLUMN IF NOT EXISTS env_lab_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS env_lab_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS env_lab_executado_por varchar,
  ADD COLUMN IF NOT EXISTS env_lab_data date,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executado_por varchar,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_data date,
  ADD COLUMN IF NOT EXISTS prova_coping_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS prova_coping_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS prova_coping_executado_por varchar,
  ADD COLUMN IF NOT EXISTS prova_coping_data date,
  ADD COLUMN IF NOT EXISTS envio_lb_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS envio_lb_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS envio_lb_executado_por varchar,
  ADD COLUMN IF NOT EXISTS envio_lb_data date,
  ADD COLUMN IF NOT EXISTS recebimento_lab_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS recebimento_lab_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS recebimento_lab_executado_por varchar,
  ADD COLUMN IF NOT EXISTS recebimento_lab_data date,
  ADD COLUMN IF NOT EXISTS paciente3_executor_id uuid REFERENCES dentistas(id),
  ADD COLUMN IF NOT EXISTS paciente3_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS paciente3_executado_por varchar,
  ADD COLUMN IF NOT EXISTS paciente3_data date;

-- procedimentos_lab_externo (mesmas etapas)
ALTER TABLE procedimentos_lab_externo
  ADD COLUMN IF NOT EXISTS escaner_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS escaner_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS escaner_executado_por varchar,
  ADD COLUMN IF NOT EXISTS escaner_data date,
  ADD COLUMN IF NOT EXISTS envio_arquivo_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS envio_arquivo_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS envio_arquivo_executado_por varchar,
  ADD COLUMN IF NOT EXISTS envio_arquivo_data date,
  ADD COLUMN IF NOT EXISTS moldagem_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS moldagem_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS moldagem_executado_por varchar,
  ADD COLUMN IF NOT EXISTS moldagem_data date,
  ADD COLUMN IF NOT EXISTS vg_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS vg_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS vg_executado_por varchar,
  ADD COLUMN IF NOT EXISTS vg_data date,
  ADD COLUMN IF NOT EXISTS env_lab_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS env_lab_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS env_lab_executado_por varchar,
  ADD COLUMN IF NOT EXISTS env_lab_data date,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_executado_por varchar,
  ADD COLUMN IF NOT EXISTS rec_lab_copping_data date,
  ADD COLUMN IF NOT EXISTS prova_coping_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS prova_coping_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS prova_coping_executado_por varchar,
  ADD COLUMN IF NOT EXISTS prova_coping_data date,
  ADD COLUMN IF NOT EXISTS envio_lb_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS envio_lb_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS envio_lb_executado_por varchar,
  ADD COLUMN IF NOT EXISTS envio_lb_data date,
  ADD COLUMN IF NOT EXISTS recebimento_lab_executor_id bigint REFERENCES proteticos(id),
  ADD COLUMN IF NOT EXISTS recebimento_lab_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS recebimento_lab_executado_por varchar,
  ADD COLUMN IF NOT EXISTS recebimento_lab_data date,
  ADD COLUMN IF NOT EXISTS paciente3_executor_id uuid REFERENCES dentistas(id),
  ADD COLUMN IF NOT EXISTS paciente3_executado_em timestamp,
  ADD COLUMN IF NOT EXISTS paciente3_executado_por varchar,
  ADD COLUMN IF NOT EXISTS paciente3_data date;

-- Notifica PostgREST para recarregar schema cache
NOTIFY pgrst, 'reload schema';
